stages:
  - test
  - deploy

variables:
  # Versiones de Python y Django que estás usando
  PYTHON_VERSION: "3.9"
  DJANGO_SETTINGS_MODULE: "tu_proyecto.settings"

test:
  stage: test
  image: python:${PYTHON_VERSION}
  script:
    - pip install -r requirements.txt
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Aquí puedes configurar el despliegue automático"
