name: Django CI/CD

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v2
      
      # Configurar Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Configurar la base de datos (usualmente SQLite para pruebas)
      - name: Set up database
        run: |
          python manage.py migrate

      # Ejecutar las pruebas unitarias
      - name: Run unit tests
        run: |
          python manage.py test